apiVersion: apps/v1
kind: Deployment
metadata:
  name: aalto-grades-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aalto-grades-frontend
  template:
    metadata:
      labels:
        app: aalto-grades-frontend
    spec:
      containers:
        - name: aalto-grades-frontend
          image: ghcr.io/aalto-grades/aalto-grades-frontend:main
          ports:
            - containerPort: 80